# Generated by Django 3.0.6 on 2020-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountAdmin',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'account_admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DailyNewBj',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('diagnosed', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('suspected', models.IntegerField()),
                ('asymptomatic', models.IntegerField()),
                ('cured', models.IntegerField()),
                ('abroad_in', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_new_bj',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
